name: Test and coverage action
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage
        run: npm run test
        # env:
        #   SECRET: ${{ secrets.SECRET }}

      - name: Commit coverage badge data
        # This action will commit the coverage-summary.json file to the repo.
        # It only runs if the file has changed.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update coverage report
          file_pattern: 'badges/coverage.json'
          # Optional: Add a token with push access if your repo is private
          # commit_user_name: my-github-actions-bot
          # commit_user_email: my-github-actions-bot@users.noreply.github.com
